# Auto-generated via Enterprise Terraform Refactoring Engine

# Auto-generated by Terraform Variable Refactoring Engine.
# Edits may be overwritten.



# ---------------------------------------------------------------------------
# AZURERM RESOURCE GROUP RES 0
# ---------------------------------------------------------------------------


variable "rg_res_0_name" {
  type        = string
  description = "Name for the azurerm resource group res 0."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP RES 1
# ---------------------------------------------------------------------------


variable "azurerm_container_app_res_1_max_inactive_revisions" {
  type        = number
  description = "Max inactive revisions for the azurerm container app res 1."
}


variable "azurerm_container_app_res_1_name" {
  type        = string
  description = "Name for the azurerm container app res 1."
}


variable "azurerm_container_app_res_1_resource_group_name" {
  type        = string
  description = "Resource group name for the azurerm container app res 1."
}


variable "azurerm_container_app_res_1_revision_mode" {
  type        = string
  description = "Revision mode for the azurerm container app res 1."
}


variable "azurerm_container_app_res_1_workload_profile_name" {
  type        = string
  description = "Workload profile name for the azurerm container app res 1."
}


variable "azurerm_container_app_res_1_secret" {
  type        = string
  description = "Secret for the azurerm container app res 1."
  sensitive = true
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP RES 1 IDENTITY0
# ---------------------------------------------------------------------------


variable "azurerm_container_app_res_1_identity0_type" {
  type        = string
  description = "Type for the azurerm container app res 1 identity0."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP RES 1 INGRESS0
# ---------------------------------------------------------------------------


variable "azurerm_container_app_res_1_ingress0_external_enabled" {
  type        = bool
  description = "External enabled for the azurerm container app res 1 ingress0."
}


variable "azurerm_container_app_res_1_ingress0_target_port" {
  type        = number
  description = "Target port for the azurerm container app res 1 ingress0."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP RES 1 INGRESS0 TRAFFIC WEIGHT0
# ---------------------------------------------------------------------------


variable "azurerm_container_app_res_1_ingress0_traffic_weight0_latest_revision" {
  type        = bool
  description = "Latest revision for the azurerm container app res 1 ingress0 traffic weight0."
}


variable "azurerm_container_app_res_1_ingress0_traffic_weight0_percentage" {
  type        = number
  description = "Percentage for the azurerm container app res 1 ingress0 traffic weight0."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP RES 1 REGISTRY0
# ---------------------------------------------------------------------------


variable "azurerm_container_app_res_1_registry0_password_secret_name" {
  type        = string
  description = "Password secret name for the azurerm container app res 1 registry0."
  sensitive = true
}


variable "azurerm_container_app_res_1_registry0_server" {
  type        = string
  description = "Server for the azurerm container app res 1 registry0."
}


variable "azurerm_container_app_res_1_registry0_username" {
  type        = string
  description = "Username for the azurerm container app res 1 registry0."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP RES 1 TEMPLATE0
# ---------------------------------------------------------------------------


variable "azurerm_container_app_res_1_template0_max_replicas" {
  type        = number
  description = "Max replicas for the azurerm container app res 1 template0."
}


variable "azurerm_container_app_res_1_template0_min_replicas" {
  type        = number
  description = "Min replicas for the azurerm container app res 1 template0."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP RES 1 TEMPLATE0 CONTAINER0
# ---------------------------------------------------------------------------


variable "azurerm_container_app_res_1_template0_container0_cpu" {
  type        = string
  description = "Cpu for the azurerm container app res 1 template0 container0."
}


variable "azurerm_container_app_res_1_template0_container0_image" {
  type        = string
  description = "Image for the azurerm container app res 1 template0 container0."
}


variable "azurerm_container_app_res_1_template0_container0_memory" {
  type        = string
  description = "Memory for the azurerm container app res 1 template0 container0."
}


variable "azurerm_container_app_res_1_template0_container0_name" {
  type        = string
  description = "Name for the azurerm container app res 1 template0 container0."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP RES 1 TEMPLATE0 CONTAINER0 ENV0
# ---------------------------------------------------------------------------


variable "azurerm_container_app_res_1_template0_container0_env0_name" {
  type        = string
  description = "Name for the azurerm container app res 1 template0 container0 env0."
}


variable "azurerm_container_app_res_1_template0_container0_env0_value" {
  type        = string
  description = "Value for the azurerm container app res 1 template0 container0 env0."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP RES 1 TEMPLATE0 CONTAINER0 ENV1
# ---------------------------------------------------------------------------


variable "azurerm_container_app_res_1_template0_container0_env1_name" {
  type        = string
  description = "Name for the azurerm container app res 1 template0 container0 env1."
}


variable "azurerm_container_app_res_1_template0_container0_env1_value" {
  type        = string
  description = "Value for the azurerm container app res 1 template0 container0 env1."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP ENVIRONMENT RES 2
# ---------------------------------------------------------------------------


variable "azurerm_container_app_environment_res_2_name" {
  type        = string
  description = "Name for the azurerm container app environment res 2."
}


variable "azurerm_container_app_environment_res_2_resource_group_name" {
  type        = string
  description = "Resource group name for the azurerm container app environment res 2."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP ENVIRONMENT RES 2 IDENTITY0
# ---------------------------------------------------------------------------


variable "azurerm_container_app_environment_res_2_identity0_type" {
  type        = string
  description = "Type for the azurerm container app environment res 2 identity0."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER APP ENVIRONMENT RES 2 WORKLOAD PROFILE0
# ---------------------------------------------------------------------------


variable "azurerm_container_app_environment_res_2_workload_profile0_name" {
  type        = string
  description = "Name for the azurerm container app environment res 2 workload profile0."
}


variable "azurerm_container_app_environment_res_2_workload_profile0_workload_profile_type" {
  type        = string
  description = "Workload profile type for the azurerm container app environment res 2 workload profile0."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER REGISTRY RES 3
# ---------------------------------------------------------------------------


variable "acr_res_3_admin_enabled" {
  type        = bool
  description = "Admin enabled for the azurerm container registry res 3."
}


variable "acr_res_3_name" {
  type        = string
  description = "Name for the azurerm container registry res 3."
}


variable "acr_res_3_resource_group_name" {
  type        = string
  description = "Resource group name for the azurerm container registry res 3."
}


variable "acr_res_3_sku" {
  type        = string
  description = "Sku for the azurerm container registry res 3."
  validation {
    condition     = contains(["Basic", "Standard", "Premium"], var.acr_res_3_sku)
    error_message = "SKU tier must be Basic, Standard, or Premium."
  }
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER REGISTRY SCOPE MAP RES 4
# ---------------------------------------------------------------------------


variable "azurerm_container_registry_scope_map_res_4_actions" {
  type        = list(string)
  description = "Actions for the azurerm container registry scope map res 4."
}


variable "azurerm_container_registry_scope_map_res_4_container_registry_name" {
  type        = string
  description = "Container registry name for the azurerm container registry scope map res 4."
}


variable "azurerm_container_registry_scope_map_res_4_description" {
  type        = string
  description = "Description for the azurerm container registry scope map res 4."
}


variable "azurerm_container_registry_scope_map_res_4_name" {
  type        = string
  description = "Name for the azurerm container registry scope map res 4."
}


variable "azurerm_container_registry_scope_map_res_4_resource_group_name" {
  type        = string
  description = "Resource group name for the azurerm container registry scope map res 4."
}


variable "azurerm_container_registry_scope_map_res_4_depends_on" {
  type        = list(string)
  description = "Depends on for the azurerm container registry scope map res 4."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER REGISTRY SCOPE MAP RES 5
# ---------------------------------------------------------------------------


variable "azurerm_container_registry_scope_map_res_5_actions" {
  type        = list(string)
  description = "Actions for the azurerm container registry scope map res 5."
}


variable "azurerm_container_registry_scope_map_res_5_container_registry_name" {
  type        = string
  description = "Container registry name for the azurerm container registry scope map res 5."
}


variable "azurerm_container_registry_scope_map_res_5_description" {
  type        = string
  description = "Description for the azurerm container registry scope map res 5."
}


variable "azurerm_container_registry_scope_map_res_5_name" {
  type        = string
  description = "Name for the azurerm container registry scope map res 5."
}


variable "azurerm_container_registry_scope_map_res_5_resource_group_name" {
  type        = string
  description = "Resource group name for the azurerm container registry scope map res 5."
}


variable "azurerm_container_registry_scope_map_res_5_depends_on" {
  type        = list(string)
  description = "Depends on for the azurerm container registry scope map res 5."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER REGISTRY SCOPE MAP RES 6
# ---------------------------------------------------------------------------


variable "azurerm_container_registry_scope_map_res_6_actions" {
  type        = list(string)
  description = "Actions for the azurerm container registry scope map res 6."
}


variable "azurerm_container_registry_scope_map_res_6_container_registry_name" {
  type        = string
  description = "Container registry name for the azurerm container registry scope map res 6."
}


variable "azurerm_container_registry_scope_map_res_6_description" {
  type        = string
  description = "Description for the azurerm container registry scope map res 6."
}


variable "azurerm_container_registry_scope_map_res_6_name" {
  type        = string
  description = "Name for the azurerm container registry scope map res 6."
}


variable "azurerm_container_registry_scope_map_res_6_resource_group_name" {
  type        = string
  description = "Resource group name for the azurerm container registry scope map res 6."
}


variable "azurerm_container_registry_scope_map_res_6_depends_on" {
  type        = list(string)
  description = "Depends on for the azurerm container registry scope map res 6."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER REGISTRY SCOPE MAP RES 7
# ---------------------------------------------------------------------------


variable "azurerm_container_registry_scope_map_res_7_actions" {
  type        = list(string)
  description = "Actions for the azurerm container registry scope map res 7."
}


variable "azurerm_container_registry_scope_map_res_7_container_registry_name" {
  type        = string
  description = "Container registry name for the azurerm container registry scope map res 7."
}


variable "azurerm_container_registry_scope_map_res_7_description" {
  type        = string
  description = "Description for the azurerm container registry scope map res 7."
}


variable "azurerm_container_registry_scope_map_res_7_name" {
  type        = string
  description = "Name for the azurerm container registry scope map res 7."
}


variable "azurerm_container_registry_scope_map_res_7_resource_group_name" {
  type        = string
  description = "Resource group name for the azurerm container registry scope map res 7."
}


variable "azurerm_container_registry_scope_map_res_7_depends_on" {
  type        = list(string)
  description = "Depends on for the azurerm container registry scope map res 7."
}



# ---------------------------------------------------------------------------
# AZURERM CONTAINER REGISTRY SCOPE MAP RES 8
# ---------------------------------------------------------------------------


variable "azurerm_container_registry_scope_map_res_8_actions" {
  type        = list(string)
  description = "Actions for the azurerm container registry scope map res 8."
}


variable "azurerm_container_registry_scope_map_res_8_container_registry_name" {
  type        = string
  description = "Container registry name for the azurerm container registry scope map res 8."
}


variable "azurerm_container_registry_scope_map_res_8_description" {
  type        = string
  description = "Description for the azurerm container registry scope map res 8."
}


variable "azurerm_container_registry_scope_map_res_8_name" {
  type        = string
  description = "Name for the azurerm container registry scope map res 8."
}


variable "azurerm_container_registry_scope_map_res_8_resource_group_name" {
  type        = string
  description = "Resource group name for the azurerm container registry scope map res 8."
}


variable "azurerm_container_registry_scope_map_res_8_depends_on" {
  type        = list(string)
  description = "Depends on for the azurerm container registry scope map res 8."
}



# ---------------------------------------------------------------------------
# AZURERM LOG ANALYTICS WORKSPACE RES 9
# ---------------------------------------------------------------------------


variable "azurerm_log_analytics_workspace_res_9_name" {
  type        = string
  description = "Name for the azurerm log analytics workspace res 9."
}


variable "azurerm_log_analytics_workspace_res_9_resource_group_name" {
  type        = string
  description = "Resource group name for the azurerm log analytics workspace res 9."
}



# ---------------------------------------------------------------------------
# AZURERM STORAGE ACCOUNT RES 684
# ---------------------------------------------------------------------------


variable "stg_res_684_account_replication_type" {
  type        = string
  description = "Account replication type for the azurerm storage account res 684."
}


variable "stg_res_684_account_tier" {
  type        = string
  description = "Account tier for the azurerm storage account res 684."
  validation {
    condition     = contains(["Basic", "Standard", "Premium"], var.stg_res_684_account_tier)
    error_message = "SKU tier must be Basic, Standard, or Premium."
  }
}


variable "stg_res_684_allow_nested_items_to_be_public" {
  type        = bool
  description = "Allow nested items to be public for the azurerm storage account res 684."
}


variable "stg_res_684_name" {
  type        = string
  description = "Name for the azurerm storage account res 684."
}


variable "stg_res_684_resource_group_name" {
  type        = string
  description = "Resource group name for the azurerm storage account res 684."
}



# ---------------------------------------------------------------------------
# AZURERM STORAGE CONTAINER RES 686
# ---------------------------------------------------------------------------


variable "azurerm_storage_container_res_686_name" {
  type        = string
  description = "Name for the azurerm storage container res 686."
}



# ---------------------------------------------------------------------------
# AZURERM STORAGE CONTAINER RES 687
# ---------------------------------------------------------------------------


variable "azurerm_storage_container_res_687_name" {
  type        = string
  description = "Name for the azurerm storage container res 687."
}



# ---------------------------------------------------------------------------
# AZURERM STORAGE ACCOUNT QUEUE PROPERTIES RES 689 HOUR METRICS0
# ---------------------------------------------------------------------------


variable "azurerm_storage_account_queue_properties_res_689_hour_metrics0_version" {
  type        = string
  description = "Version for the azurerm storage account queue properties res 689 hour metrics0."
}



# ---------------------------------------------------------------------------
# AZURERM STORAGE ACCOUNT QUEUE PROPERTIES RES 689 LOGGING0
# ---------------------------------------------------------------------------


variable "azurerm_storage_account_queue_properties_res_689_logging0_delete" {
  type        = bool
  description = "Delete for the azurerm storage account queue properties res 689 logging0."
}


variable "azurerm_storage_account_queue_properties_res_689_logging0_read" {
  type        = bool
  description = "Read for the azurerm storage account queue properties res 689 logging0."
}


variable "azurerm_storage_account_queue_properties_res_689_logging0_version" {
  type        = string
  description = "Version for the azurerm storage account queue properties res 689 logging0."
}


variable "azurerm_storage_account_queue_properties_res_689_logging0_write" {
  type        = bool
  description = "Write for the azurerm storage account queue properties res 689 logging0."
}



# ---------------------------------------------------------------------------
# AZURERM STORAGE ACCOUNT QUEUE PROPERTIES RES 689 MINUTE METRICS0
# ---------------------------------------------------------------------------


variable "azurerm_storage_account_queue_properties_res_689_minute_metrics0_version" {
  type        = string
  description = "Version for the azurerm storage account queue properties res 689 minute metrics0."
}


variable "resource_group_name" {
  description = "The name of the Azure resource group."
  type = string
  default = "rg-mcp-servers"
}
